### ISSUE TITLE
How to get the 'avc1' sample entry from sampleDescription (stsd)?

### ISSUE THREAD

**Issue by hengshaochen** [MPEGGroup/isobmff#10]
Hi,

I try many different ways but still can not get the avc1 box information such as width, height, and extensionList point to avcC.

First, I open the file and get moov and then get track... and so on.
	err = ISOOpenMovieFile( &moov, filename, MP4OpenMovieNormal );
	err = ISOGetMovieIndTrack( moov, trackNumber, &trak );
	err = ISOGetTrackMedia( trak, &media );

Then, I get sampleDescription box.
	stsd = (MP4SampleDescriptionAtomPtr) stbl->SampleDescription;	

Then, I want get the avc1 box in stsd. But stsd only have method call: getEntry( struct MP4SampleDescriptionAtom *self, u32 entryNumber,  struct GenericSampleEntryAtom **outEntry )

The problem is the outEntry is GenericSampleEntryAtom, but I may need to use MP4VisualSampleEntryAtom as output. If that possible way to transfer GenericSampleEntryAtom to MP4VisualSampleEntryAtomPtr? Or is there is other way to get avc1 box information?

Thanks!

**Comment by dwsinger** [comment]
Hi

have you looked at ISOGetAVCSampleDescription, ISOGetVCSampleDescriptionPS, and so on?

> On Aug 1, 2018, at 16:37 , hengshaochen <notifications@github.com> wrote:
> 
> Hi,
> 
> I try many different ways but still can not get the avc1 box information such as width, height, and extensionList point to avcC.
> 
> First, I open the file and get moov and then get track... and so on.
> err = ISOOpenMovieFile( &moov, filename, MP4OpenMovieNormal );
> err = ISOGetMovieIndTrack( moov, trackNumber, &trak );
> err = ISOGetTrackMedia( trak, &media );
> 
> Then, I get sampleDescription box.
> stsd = (MP4SampleDescriptionAtomPtr) stbl->SampleDescription;
> 
> Then, I want get the avc1 box in stsd. But stsd only have method call: getEntry( struct MP4SampleDescriptionAtom *self, u32 entryNumber, struct GenericSampleEntryAtom **outEntry )
> 
> The problem is the outEntry is GenericSampleEntryAtom, but I may need to use MP4VisualSampleEntryAtom as output. If that possible way to transfer GenericSampleEntryAtom to MP4VisualSampleEntryAtomPtr? Or is there is other way to get avc1 box information?
> 
> Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by hengshaochen** [comment]
Hi David,

Thanks for your quick reply.

I checked "ISOGetAVCSampleDescription" function. But this function need MP4Handle sampleEntryH as a input parameter. I try many different way to generate the correct sampleEntryH parameter, such as:

	MP4AtomPtr atomPtr = NULL;
	MP4Handle sampleEntryH;
	MP4NewHandle(152, &sampleEntryH);  // size of avc1 box is 152
	stsd->getEntry(stsd, 1,  &atomPtr);    // the avc1 box is in idx = 1, and put avc1 box into atomPtr
	atomPtrToSampleEntryH(&sampleEntryH, atomPtr);

But in this way, the atomPtr is still GenericSampleEntryAtom not a MP4VisualSampleEntryAtomPtr. I am confusing in how to get the sampleEntryH...

Thanks for your help.

**Comment by hengshaochen** [comment]
I double check the document about ISOHandle. "It is common to create a zero-length Handle and pass it to a function that places data into it, resizing it appropriately. You can treat handles as (char**) as long as you use the API functions to allocate their memory and change their size."

And I only see the ISOPutMovieIntoHandle method to generate ISOHandle from moov. But now I think I need to generate ISOHandle from stsd->avc1. Is that any way to achieve that? Thanks!

**Comment by dwsinger** [comment]
I confess that the support for fiddling with sample entry boxes is not great. I fear you’ll need to read examples. The functions I pointed you at might help, or some of the other example applications.

There are functions indeed to put boxes into handles, and parse them from handles.

> On Aug 1, 2018, at 17:50 , hengshaochen <notifications@github.com> wrote:
> 
> I double check the document about ISOHandle. "It is common to create a zero-length Handle and pass it to a function that places data into it, resizing it appropriately. You can treat handles as (char**) as long as you use the API functions to allocate their memory and change their size."
> 
> And I only see the ISOPutMovieIntoHandle method to generate ISOHandle from moov. But now I think I need to generate ISOHandle from stsd->avc1. Is that any way to achieve that? Thanks!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by ahmedhmz** [comment]
Have you tried using a track reader? If you create a track reader object, you can use the MP4TrackReaderGetCurrentSampleDescription() function. You can then get the sample description type by calling ISOGetSampleDescriptionType() and checking against the type you expect.

```
ISOErr err;
ISOHandle sampleEntryH;
u32 sampleDescriptionType;
err = ISONewHandle(1, &sampleEntryH); 
// assuming you have created a track reader object earlier
err = MP4TrackReaderGetCurrentSampleDescription(reader, sampleEntryH);
err = ISOGetSampleDescriptionType(sampleEntryH, &sampleDescriptionType);
```

**Comment by hengshaochen** [comment]
Thanks @dwsinger and @ahmedhmz for giving me some great direction.

I use generate ISOHandle from MP4VisualSampleEntryAtomPtr (some field is not parse correctly, such as width and height, but that is ok). Then transfer the ISOHandle to MP4VisualSampleEntryAtomPtr by using sampleEntryHToAtomPtr() function, then we can get the correct MP4VisualSampleEntryAtomPtr (all field is correct).

Thanks again.

Code for reference if someone have the same issue:

	ISOHandle sampleEntryH;
	MP4VisualSampleEntryAtomPtr atomPtr = NULL;
	ISONewHandle(0, &sampleEntryH);
	stsd2->getEntry(stsd2, 1,  &atomPtr);
	atomPtrToSampleEntryH( sampleEntryH, atomPtr );
	MP4VisualSampleEntryAtomPtr avc1Ptr;
	ISOVCConfigAtomPtr			 config;

	err = sampleEntryHToAtomPtr( sampleEntryH, (MP4AtomPtr *) &avc1Ptr, MP4VisualSampleEntryAtomType ); if (err) goto bail;
	if (avc1Ptr->type != ISOAVCSampleEntryAtomType) BAILWITHERROR( MP4BadParamErr );
	err = MP4GetListEntryAtom( avc1Ptr->ExtensionAtomList, ISOVCConfigAtomType, (MP4AtomPtr*) &config ); 
	if ( err == MP4NotFoundErr )
	{
	  BAILWITHERROR( MP4BadDataErr );
	}
