### ISSUE TITLE
Submodule issue: Failed to clone 'IsoLib/HM'

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/isobmff#17]
I just noticed that git://hevc.kw.bbc.co.uk/git/jctvc-hm.git seems to be down. Therefore HM submodule can not be cloned when attempting to build `IsoLib`

>  $ cmake ..
> -- ...
> -- Detecting CXX compile features - done
> -- Submodule update
> Submodule 'IsoLib/HM' (git://hevc.kw.bbc.co.uk/git/jctvc-hm.git) registered for path 'IsoLib/HM'
> Cloning into '/Users/podborski/projects/isobmff/IsoLib/HM'...
> fatal: unable to connect to hevc.kw.bbc.co.uk:
> hevc.kw.bbc.co.uk[0: 132.185.142.226]: errno=Operation timed out
> 
> fatal: clone of 'git://hevc.kw.bbc.co.uk/git/jctvc-hm.git' into submodule path '/Users/podborski/projects/isobmff/IsoLib/HM' failed
> Failed to clone 'IsoLib/HM'. Retry scheduled
> Cloning into '/Users/podborski/projects/isobmff/IsoLib/HM'...
> fatal: unable to connect to hevc.kw.bbc.co.uk:
> hevc.kw.bbc.co.uk[0: 132.185.142.226]: errno=Operation timed out
> 

Moving it to github would be great I guess.

**Comment by dwsinger** [comment]
It seems that the link we have is a git mirror to the svn bbc mirror of the svn repository of HHI ;); Don’t ask.

I think HM is now on git 
https://vcgit.hhi.fraunhofer.de/jct-vc/HM.git

Maybe we should update?

**Comment by podborski** [comment]
I can check it on Monday.

**Comment by podborski** [comment]
yep, https://vcgit.hhi.fraunhofer.de/jct-vc/HM.git can be used since it is the newest git repo of HM.

**Comment by dwsinger** [comment]
@podborski do you have a proposed update?

**Comment by podborski** [comment]
@dwsinger BBC link seems to work again. But in case we want to update to HHI one, I think [this changes](https://github.com/MPEGGroup/isobmff/compare/master...podborski:submodule) should do it. 

On macOS I have another problem compiling `hevc_demuxer` and `hevc_muxer`. This is the same with BBC and HHI submodules.

> $ make hevc_demuxer
> [ 96%] Built target libisomediafile
> [ 98%] Linking C executable hevc_demuxer
> Undefined symbols for architecture x86_64:
>   "_assert", referenced from:
>       _hevc_parse_slice_header_minimal in hevc.c.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[3]: *** [IsoLib/favs_example/hevc_demuxer] Error 1
> make[2]: *** [IsoLib/favs_example/CMakeFiles/hevc_demuxer.dir/all] Error 2
> make[1]: *** [IsoLib/favs_example/CMakeFiles/hevc_demuxer.dir/rule] Error 2
> make: *** [hevc_demuxer] Error 2

But I guess this should be discussed in a separate issue.
