### ISSUE TITLE
Make drc_in_isom build

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/isobmff#3]
drc_in_isom fails to build in Travis CI with the following error:
../src/WAVData.h:39:19: fatal error: wavIO.h: No such file or directory

**Comment by edrthomas** [comment]
Need to fix #13 first

**Comment by edrthomas** [comment]
I modified the Travis build.

It now builds all the tool and in a second job it tries to build the drc tool.

https://travis-ci.org/MPEGGroup/isobmff/builds/481469298

I marked the audio tool build as not mandatory so that the overall build is mark passed even if the audio tool fails.

**Comment by edrthomas** [comment]
The tool has been updated and the travis script now builds it by default too.

8d47fad25bb0ed9c765a1ea2060ab2f141cfcf36
