### ISSUE TITLE
Calling sprintf function with destination buffer of smaller size than size/expected size of the source

### ISSUE THREAD

**Issue by gurdep** [MPEGGroup/isobmff#44]
Compiling the project with GCC 11.2.0 on a x86_64 arch. 

There are few instances where the compiler throws an overflow error that could potentially cause issues.

Following is the error statement from the compiler:
> error: ‘%s’ directive writing up to 4095 bytes into a region of size 188 [-Werror=format-overflow=]
  282 |     sprintf(msgString, "itemName = '%s'", self->item_name);

https://github.com/MPEGGroup/isobmff/blob/2a0e1a3690efb4553defca31caf347013f1eb9e1/IsoLib/libisomediafile/src/ItemInfoEntryAtom.c#L282

Similar error was observed in the following instances
https://github.com/MPEGGroup/isobmff/blob/2a0e1a3690efb4553defca31caf347013f1eb9e1/IsoLib/libisomediafile/src/XMLMetaSampleEntry.c#L159

https://github.com/MPEGGroup/isobmff/blob/2a0e1a3690efb4553defca31caf347013f1eb9e1/IsoLib/libisomediafile/src/TextMetaSampleEntry.c#L144

To mitigate the issue, some suggestions are provided:
1. Easy fix: The size of buffer can be made large enough to contain the entire resulting string. 
2. Maybe use `snprintf` which is a safer option than `sprintf`. 

Any thoughts? @podborski

**Comment by podborski** [comment]
Should be fixed in `sgpd_versions` branch that we want to merge soon. If not please re-open this issue.
