### ISSUE TITLE
Request the clang-format.yml file change some version

### ISSUE THREAD

**Issue by ohjiwoo123** [MPEGGroup/isobmff#53]
I think that you need to change the clang-format.yml file (version up)    
If I use jidicula/clang-format-action@v4.4.1 version, The error raised like below.
```
Installing clang-format-13
E: Unable to locate package clang-format-13
Not a directory in the workspace, fallback to all files.
/entrypoint.sh: line 23: /usr/bin/clang-format-13: No such file or directory
```
https://github.com/MPEGGroup/isobmff/blob/master/.github/workflows/clang-format.yml   

jidicula/clang-format-action@v4.4.1 -> jidicula/clang-format-action@v4.11.0  
or  
jidicula/clang-format-action@v4.9.0   
Thank you

**Comment by podborski** [comment]
I think this was addressed in https://github.com/MPEGGroup/isobmff/pull/55 I merged it in the sgpd_versions that is in another PR https://github.com/MPEGGroup/isobmff/pull/41. This will be merged after review.
